services:
  app:
    build: .
    tty: true
    volumes:
      - ./:/workspace/
    container_name: cs_ex_calendar
    environment:
      JAVA_OPTS: "-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dorg.apache.catalina.connector.CoyoteAdapter.parseBodyMethods=POST,PUT,PATCH,DELETE"
    ports:
      - 8080:8080
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: java
      MYSQL_USER: java
      MYSQL_PASSWORD: java
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/log:/var/log/mysql
    ports:
      - 3360:3306